title: marks
email: mark@marks.dk
description: >- # this means to ignore newlines until "baseurl:"
  It never gets easier, you just go faster.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: marks
github_username: marksdk
destination: ./_site
permalink: pretty

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed